version: '3.3'
services:
 app:
  image: variable21/emsapp
  ports:
   - "8080:8080"
  enviorment:
   SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/demo?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
   SPRING_DATASOURCE_USERNAME: root
   SPRING_DATASOURCE_PASSWORD: hi@123
  depends_on:
 db:
  image: mysql:8.0.29
  enviorment:
   MYSQL_USER: root
   MYSQL_ROOT_PASSWORD: hi@123
   MYSQL_DATABASE: demo
  ports:
   - "3306:3306"
   

   